version: '3'
services:
  api-mobile:
    image: basic-api:master-v1  
    environment:
     - FLASK_APP=run.py
    links:
      - redis  
    ports:
      - "8080:8080"

  redis:
    image: redis:4.0.9
    ports:
      - "6379:6379"
